### ISSUE TITLE
Add Support for other hashing algorithms

### ISSUE THREAD

**Issue by kx06** [acmpesuecc/myGit_hn6#3]
Currently the hash-object function uses sha512 by default, make it use a different hashing algorithm like sha256 when a flag of your choice is passed.

**Comment by devanshishukla17** [comment]
can I get this assigned?

**Comment by kx06** [comment]
!assign @devanshishukla17

**Comment by kx06** [comment]
!extend 30

**Comment by devanshishukla17** [comment]
HI I have made the changes from what I read. I am going for dinner. I'll come back and make changes if required

**Comment by kx06** [comment]
!extend 60

**Comment by kx06** [comment]
!deassign

**Comment by kx06** [comment]
!assign @devanshishukla17 60

**Comment by Rohini-Lakkimsetty** [comment]
can i get assigned to this?

**Comment by kx06** [comment]
!deassign

**Comment by kx06** [comment]
!assign @devanshishukla17

**Comment by kx06** [comment]
@Rohini-Lakkimsetty sorry the previous person is pretty close, if they aren't able to do it in 30 mins ill assign it to you

**Comment by kx06** [comment]
!deassign

**Comment by kx06** [comment]
!deassign @devanshishukla17
